#version: '3' # docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync project dir with container web dir
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=note_managemer # database name here
      - MYSQL_USER=php_docker # username for phpmyadmin
      - MYSQL_PASSWORD=password # password for phpmyadmin / this should be an empty var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./config/docker-entrypoint-initdb.d" # sync persistent sql files with container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PHA_PORT=3306