version: '3.8'
services:
  # PHP + Apache Service
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"              # Map port 80 của container tới port 8080 trên máy
    volumes:
      - "./:/var/www/html"    # sync project dir with container web dir / Đồng bộ mã nguồn
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - mysql                  # PHP phụ thuộc vào MySQL
    networks:
      - backend

  # MySQL Service
  mysql:
    image: mysql:8.4.2           # Sử dụng MySQL phiên bản 8.4.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass   # root password
      MYSQL_DATABASE: note_manager          # default database name
      MYSQL_USER: user               # default user name
      MYSQL_PASSWORD: userpass     # password for user
    volumes:
      - "./data:/docker-entrypoint-initdb.d" # sync persistent sql files with container
    ports:
      - "3306:3306"            # Map port 3306
    networks:
      - backend

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"              # Map port 80 của phpMyAdmin tới 8081
    environment:
      PMA_HOST: mysql          # MySQL Host (trùng với tên service)
      MYSQL_ROOT_PASSWORD: rootpass       # root password
    depends_on:
      - mysql
    networks:
      - backend

  # WebSocket Server
  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    depends_on:
      - mysql
    networks:
      - backend
    # Optional: expose port if needed for testing from host
    ports:
      - "8082:8082"

networks:
  backend:
    driver: bridge